name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libappindicator3-dev librsvg2-dev
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Build Tauri
      run: cargo tauri build --verbose
    - name: Run tests
      run: cargo test --verbose
